<?php
use \Firebase\JWT\JWT;
// docs: http://www.sitepoint.com/php-authorization-jwt-json-web-tokens/
//       http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs

/* ***************************************************************************************************
** AUTH INIT *****************************************************************************************
*************************************************************************************************** */ 

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	$request['content'] = json_decode(file_get_contents("php://input"),true);
	api_signin($request, $config);
} else{
	api_forbidden($config);
};

/* ***************************************************************************************************
** AUTH SIGNIN FUNCTIONS *****************************************************************************
*************************************************************************************************** */ 

function api_signin($request, $config){

	// VALIDATE CREDENTIALS
	$userCredentials = array(
		'email' => $request['content']['email'],
		'password' => md5($request['content']['password']),
	);

	$user = R::findOne('user', 'email = :email and password = :password and active = true', $userCredentials );

	// IF USER EXISTS
	if(!empty($user)){

		$tokenId    = base64_encode(mcrypt_create_iv(32));
		$issuedAt   = R::isoDateTime();
		$notBefore  = $issuedAt + 10; 				// Adding 10 seconds
		$expire     = $notBefore + 60; 				// Adding 60 seconds
		$serverName = $config['auth']['jwtIssuer']; // Retrieve the server name from config file
	
		// create the token as an array
		$data = [
			'iat'  => $issuedAt, 					// Issued at: time when the token was generated
			'jti'  => $tokenId, 					// Json Token Id: an unique identifier for the token
			'iss'  => $serverName, 					// Issuer
			'nbf'  => $notBefore, 					// Not before
			'exp'  => $expire, 						// Expire
			'data' => [ 							// Data related to the signer user from the users table
				'id'   	=> $user['id'],
				'name' 	=> $user['name'],
				'email' => $userCredentials['email'],
			]
		];

		// extract the secret key from the config file. 
		// the key is generated by using: base64_encode(openssl_random_pseudo_bytes(64));
		$secretKey = base64_decode($config['auth']['jwtKey']);
	
		// encode the array to a JWT string.
		// the output string can be validated at http://jwt.io/
		$jwt = JWT::encode(
			$data, 		// Data to be encoded in the JWT
			$secretKey, // The signing key
			'HS512' 	// Algorithm used to sign the token, see https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3
		);

		$unencodedArray = ['jwt' => $jwt];
 		$result['token'] = $jwt;
	}

	// IF USER DOES NOT EXISTS
	else {
		header('HTTP/1.0 401 Unauthorized');
	}	

	// OUTPUT
	api_output($result);

};

?>