<?php
return array(

	// $config DB (MySQL Database)
	'db' => [
		'host' => 'mysql:host=186.202.152.193; dbname=umstudiohomolo12',
		'user' => 'umstudiohomolo12',
		'pass' => 'studio0001',
	],

	// $config AUTH (JWT - JSON Web Token)
	'auth' => [
		'jwtKey' 	=> 'VYFBH3XEduP724aIhZESyk3Ru+h3sxI5w0nbRwnYrrbymjvnf3ZCWkqJO26V4AhYQAtQk02dHO1wbi4Xjs9QUA==',
						// the key is generated by using: base64_encode(openssl_random_pseudo_bytes(64));
		'jwtIssuer' => $_SERVER['HTTP_HOST'],
		'jwtExpire' => 3600,	
	],

	// CONFIG API (Global Values)
	'api' => [
		'debug' 	=> TRUE,
		'locale' 	=> 'pt_BR',
		'actions' 	=> array(
			'get' 	=> array('hi', 'edges', 'search', 'list', 'read', 'count', 'schema', 'exists', 'export'),
			'post' 	=> array('create', 'update','updatePassword', 'upload', 'destroy'),
		),
		'edges'		=> array(
			'blacklist' 	=> array('uploads','page_uploads'),
			),
		'params' => array(
			'pagination' => 5,
		),
		'uploads' => array(
			'basepath' => '../uploads/',
		),
	],

	// CONFIG SCHEMA DEFAULTS (Form Builder)
	'schema' => [
		'default' => array(
			'blacklist' 	=> array('id','created','modified'),
			'type' 			=> array(
				'date' 		=> 'string',
				'int' 		=> 'integer',
				'text' 		=> 'string',
				'tinyint' 	=> 'boolean',
				'varchar' 	=> 'string',
			),
			'format' 		=> array(
				'varchar' 	=> 'string',
				'int' 		=> 'number',
				'date' 		=> 'date',
				'text' 		=> 'textarea',
				'tinyint' 	=> 'checkbox',
			),
		),
		'custom' => array(
			'fields' => array(
				'description' => array(
					'type'		=> 'string',
					'format'	=> 'html',
					'options' 	=> array(
						'wysiwyg' 	=> true,
						),
				),
				'email' => array(
					'format' 	=> 'email',
				),
				'phone' => array(
					'format' 	=> 'tel',
				),
				'password' => array(
					'type' 		=> 'string',
					'format' 	=> 'password',
				),
			),
		)
	]
	
);

?>